import "./styles/globals.css"
import { BlitzProvider } from "./blitz-client"
import { Inter } from "next/font/google"
import { ThemeModeScript } from "flowbite-react"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Flowbite React Template Blitz",
  template: "%s – Blitz",
  description: "Generated by blitz new ",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <BlitzProvider>
          <>{children}</>
        </BlitzProvider>
      </body>
    </html>
  )
}
